### ISSUE TITLE
Мелкие правки 

### ISSUE THREAD

**Issue by Olga-Skoroded** [Kiril-ML/uniswap#4]
Заметила пару опечаток в проекте, наверное должно быть amou**n**t и **on**Close)) рекомендую поставить code spell checker для vscode или что-то подобное)
![Снимок экрана от 2022-06-30 09-52-56](https://user-images.githubusercontent.com/68814270/176614635-759394af-b5b9-4da1-94d9-3fb20b34b3cc.png)
![Снимок экрана от 2022-06-30 09-53-17](https://user-images.githubusercontent.com/68814270/176614661-9a7304b5-1e32-453d-9a3d-6bdca9bfc26e.png)

**Comment by Olga-Skoroded** [comment]
Для таких условий, мне кажется, тернарник напрашивается 
![Снимок экрана от 2022-06-30 09-59-39](https://user-images.githubusercontent.com/68814270/176615508-35ae61fe-0eee-42f1-ad7b-7c671bf6b162.png)

**Comment by Kiril-ML** [comment]
По поводу amount, это опечатка в методе смарт-контракта
![image](https://user-images.githubusercontent.com/106853686/176616234-4c193f89-9bd7-4dfc-aa29-9750ba6bd877.png)
[Ссылка](https://rinkeby.etherscan.io/address/0xeCB9c90D61b2105658540E0436b14b4e07A0E7b2#readContract)
